name: Create PyPI release

on:
  push:
    tags:
      - '*'

jobs:
  build-n-publish:
    name: Create PyPI release
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@main
    - name: Create environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: create wheel
      run: |
        python -m pip install --user --upgrade setuptools wheel
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
